### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.3

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by bgruening** [comment]
Cool! Thanks all merged before US wake up! :)

**Comment by jdblischak** [comment]
Thanks, @bgruening! It's always nice to wake up to merged PRs :-)

**Comment by bgruening** [comment]
Your welcome!
Not so nice is that staged-recipes are building again against 3.4.2 :(

**Comment by jdblischak** [comment]
> Not so nice is that staged-recipes are building again against 3.4.2 :(

Ugh. So frustrating! Please let me know if you need any help with this.

**Pull request merged**
