### PR TITLE
Update of r-bookdown that ought to fix issue with updated pandoc

### PR DESCRIPTION
**Pull request by bsennblad**
Various compatibility issues with Pandoc 2.0, which is fixed as of bookdown v0.6, prompted an update of this conda package to version 0.6.

Notifying package maintainers:
@jdblischak 
@bgruening 
@johanneskoester

### CODE REVIEW

**Comment by bsennblad** [comment]
@jdblischak Oops! I just saw that you were not listed as maintainer for this package as I assumed when submitting the PR (since you are usually automatically added, e.g., by conda_r_skeleton_helper). Do you want me to add you as maintainer? (and maybe @daler too?).

**Comment by jdblischak** [comment]
@bsennblad Please run it through helper script and replace all the files. Also do `git rm recipe/LICENSE.txt` since that is no longer needed (the helper script grabs the license file from the one shipped with r-base).

**Comment by jdblischak** [comment]
@bsennblad I see you're still having problems running the helper script on macOS (https://github.com/bgruening/conda_r_skeleton_helper/pull/9). Sorry about that. I just don't know enough about the peculiarities of `sed` on macOS to be of much help.

The lines should look like this:

```
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
```

**Comment by bsennblad** [comment]
@jdblischak 
I think I had a working solution to the macosx-issues in conda_r_skeleton_helper and I thought that I shared it with Björn, but I will have to dig back to see if I really managed to do it and in which way I in that case did it (I don’t seem to find a PR from me). I was rather stressed and a bit ill, so maybe I misremember about sharing it.
In any case, my solution apparently contains a issue that it seems to remove the backslash in ’\n’ at some places. 
I’ll have a little more time now so I should be able to look into it. 
I guess the way to go is to fork the Björn’s github repo, make changes and submit a PR, as usual, right?

Bengt

**Comment by jdblischak** [comment]
> I guess the way to go is to fork the Björn’s github repo, make changes and submit a PR, as usual, right?

Yes! A PR would be most welcome. It is definitely a hindrance that macOS users cannot easily run the helper script.

**Comment by bsennblad** [comment]
@jdblischak 
Do you know why appveyor fails? Error message is::

The batch file cannot be found

This didn't tell me anything, and the only thing I found on the file was the 'license'-issue for win in the meta.yaml, so I fixed that and pushed. Apparently that did not help (a bit of wishful thinking there, I guess).

BTW. Once the PR pass the tests, should I (as I am a maintainer) merge it? You have approved, do we need more approval? What's the approved sequence of actions? Which option should I use in that case ('squash and merge', 'rebase and merge 'or just 'merge pull request')?

thanks,

**Comment by jdblischak** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
> Do you know why appveyor fails? Error message is::The batch file cannot be found

Yes, the error message doesn't help much because it is a total failure. This issue was caused by changes introduced between conda 4.3 and 4.4 in how Windows scripts are run. The rerendering script updates the AppVeyor script to fix this. My comment above triggers the rerendering.

https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

> BTW. Once the PR pass the tests, should I (as I am a maintainer) merge it? You have approved, do we need more approval? What's the approved sequence of actions?

This is dependent on how big the change is. Your PR is a straightforward update of the package version. If all the CI builds pass, you could merge this yourself. Having the approval of another maintainer is nice, but not strictly necessary. The most common mistake I find is when someone bumps the version number and the SHA, but doesn't update the dependencies. I always recommend running `conda skeleton cran` (alone or via the helper script) to check if the dependencies have been changed.

> Which option should I use in that case ('squash and merge', 'rebase and merge 'or just 'merge pull request')?

For conda-forge feedstocks, I just use the default merge option since it is straightforward (and I don't care much about the commit history for these feedstocks).

**Comment by bsennblad** [comment]
@jdblischak 
Great! Thanks for all info and help, 
Bengt

**Comment by bgruening** [comment]
Wuha, great stuff! Thanks!

**Pull request merged**
